language: java
jdk:
- oraclejdk8
after_success:
- mvn site
- cd ./target/site
- touch .nojekyll
- git config --global user.email "hgcummings.jarspec@travis-ci.org"
- git config --global user.name "Travis CI"
- git init
- git remote add origin https://$GITHUB_USER:$GITHUB_PASS@github.com/hgcummings/jarspec.git
- git checkout -b gh-pages
- git add .
- git commit -m "Update maven generated site"
- git push -fq origin gh-pages
env:
  global:
  - secure: M3NfQJJ4eAo6iLNH1+/fpOnPnb5LwnrvPfxsb8KeP9Cn5I6p0Ga3uBsHYgxEZu/DygocDNLdzZJ5WF3Z49wtHXPdnWB5Ui1s42sbXczLhGVDKu6VOo8Z0oMLTKSiRwb1LOMxOVCBa1FZo+Zv5HGFTJCyPs3B7w9Lla7S+13KCLw=
  - secure: Umn7Lgz/h/6WW0Q0CMPCjEIDGcqARE6/GvN9/CFx576F/nICzWxhKicfyWUmEf2LXZ43/7qCyC58m0zP4q7gzUteCCSu/TL1YMuhu7DYwm535eTiKWDUpVJo0+dqdqU4e/97lcetqwL93LJNKmEUOwI3BVhp+5DCxZFLOGvZb8Y=