language: java
jdk:
- oraclejdk8
env:
  global:
    secure: fK/qZvODLsMfqoJ5fP/tQPToW+XuqrJcgcGKoxFOYXVBbPbSN3tPXG6UHhM9q0oploMNtQpzZtyt0MvlHXrx0eIg3ITpoJ1NngI0T7qCcUGr/u5aF2PDdwWvFIxxH6McLT8GULpYvK76i4c/s9M+v1oJdkg09YvL8TRMtlPJdUc=
after_success:
  - mvn site
  - openssl aes-256-cbc -k "$KEY_PASS" -d -a -in id_rsa.enc -out deploy_key
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - cd ./target/site
  - git config --global user.email "hgcummings.jarspec@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git init
  - git remote add origin https://github.com/hgcummings/jarspec.git
  - git checkout -b gh-pages
  - git add .
  - git commit -m "Update maven generated site"
  - git push -f origin gh-pages